-- MySQL 8.0+
-- ใช้ utf8mb4 เพื่อรองรับข้อมูลภาษาไทย
CREATE DATABASE IF NOT EXISTS `cafe_amazon_promotion`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `cafe_amazon_promotion`;

CREATE TABLE IF NOT EXISTS `Cafe_Amazon_Promosion_House` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Detail` TEXT DEFAULT NULL,
  `Remark` TEXT DEFAULT NULL,
  `Name` VARCHAR(255) NOT NULL,                           -- ปรับจาก LONGTEXT เป็น VARCHAR(255) เพื่อประหยัดพื้นที่และรองรับ Index
  `Phone_No` VARCHAR(13) NOT NULL,
  `Day_Limit` INT NOT NULL DEFAULT 1,
  `All_Limit` INT NOT NULL DEFAULT 50,
  `All_Use` INT NOT NULL DEFAULT 0,
  `LastUse_Date` DATETIME NULL DEFAULT NULL,
  `IsUse` TINYINT(1) NOT NULL DEFAULT 0,                  -- ปรับเป็น TINYINT(1) ซึ่งเป็น Data Type มาตรฐานของ Boolean ใน MySQL
  `InsertDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `InsertUser` VARCHAR(20) NOT NULL,
  `UpdateDate` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `UpdateUser` VARCHAR(20) NULL DEFAULT NULL,
  `PassWord` VARCHAR(255) NULL DEFAULT NULL,
  `Confirm_Coupon` TINYINT(1) NOT NULL DEFAULT 0,
  `Coupon_No` VARCHAR(50) NULL DEFAULT NULL,
  `Product_ID` VARCHAR(13) NULL DEFAULT NULL,
  `Access_Level` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UX_CafeAmazonHouse_Phone` (`Phone_No`),
  INDEX `IX_CafeAmazonHouse_Detail` (`Detail`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- ตัวอย่างเพิ่มข้อมูล (แก้ค่าตามข้อมูลจริงก่อนใช้งาน)
-- INSERT INTO `Cafe_Amazon_Promosion_House`
-- (`Detail`, `Remark`, `Name`, `Phone_No`, `Day_Limit`, `All_Limit`, `IsUse`, `InsertUser`, `ID_Company`, `ID_Branch`, `ID_Project`)
-- VALUES ('99/1', 'สมชาย ใจดี', '0812345678', 1, 1, FALSE, 'admin', 1, 1, 1);

คำสั่งสร้างเบส
--สคริปต์ SQL ที่ถูกต้องสมบูรณ์สำหรับ Supabase (PostgreSQL)
--หากคุณใช้งาน Supabase (ตามที่เห็นในไฟล์ api.js) ให้ใช้สคริปต์ชุดนี้รันใน SQL Editor ของ Supabase
/*-- 1. ลบตารางเดิมออกหากมีอยู่ (ลบ Bill ก่อนเพราะเป็นตารางลูก)
-- 1. ลบตารางเดิมออกหากมีอยู่ (ลบ Bill ก่อนเพราะเป็นตารางลูก)
DROP TABLE IF EXISTS "Cafe_Amazon_Bill";
DROP TABLE IF EXISTS "Cafe_Amazon_Promosion_House";

-- 2. สร้างตารางหลัก: Cafe_Amazon_Promosion_House
CREATE TABLE "Cafe_Amazon_Promosion_House" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Detail" TEXT DEFAULT NULL,
    "Remark" TEXT DEFAULT NULL,
    "Name" VARCHAR(255) DEFAULT NULL,
    "Phone_No" VARCHAR(13) DEFAULT NULL,
    "Day_Limit" INT DEFAULT NULL,
    "All_Limit" INT DEFAULT NULL,
    "All_Use" INT DEFAULT 0,
    "LastUse_Date" TIMESTAMPTZ DEFAULT NULL,
    "IsUse" BOOLEAN NOT NULL DEFAULT FALSE,
    "InsertDate" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "InsertUser" VARCHAR(20) DEFAULT NULL,
    "UpdateDate" TIMESTAMPTZ DEFAULT NULL,
    "UpdateUser" VARCHAR(20) DEFAULT NULL,
    "PassWord" VARCHAR(255) DEFAULT NULL,
    "Confirm_Coupon" BOOLEAN NOT NULL DEFAULT FALSE,
    "Coupon_No" VARCHAR(50) DEFAULT NULL,
    "Product_ID" VARCHAR(13) DEFAULT NULL,
    "Access_Level" INT DEFAULT 0,
    CONSTRAINT "UX_CafeAmazonHouse_Phone" UNIQUE ("Phone_No")
);

-- 3. สร้างตารางประวัติการใช้สิทธิ์/ใบเสร็จ: Cafe_Amazon_Bill
CREATE TABLE "Cafe_Amazon_Bill" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Bill_No" VARCHAR(50) DEFAULT NULL,
    "Cafe_Amazon_PK" INT REFERENCES "Cafe_Amazon_Promosion_House"("ID") ON DELETE SET NULL,
    "Product_Type" VARCHAR(13) DEFAULT NULL,
    "ItemDetail" TEXT DEFAULT NULL,
    "Price" NUMERIC(10,2) DEFAULT 0.00,
    "Discount" NUMERIC(10,2) DEFAULT 0.00,
    "Change" NUMERIC(10,2) DEFAULT 0.00,
    "InsertDate" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "IsUse" BOOLEAN DEFAULT TRUE,
    "Coupon_No" VARCHAR(50) DEFAULT NULL
);

-- 4. สร้าง Index เพื่อเพิ่มความเร็วในการค้นหา
CREATE INDEX "idx_house_coupon" ON "Cafe_Amazon_Promosion_House" ("Coupon_No");
CREATE INDEX "idx_bill_pk" ON "Cafe_Amazon_Bill" ("Cafe_Amazon_PK");

*/

-------------------------------------------------------------
--หากต้องการใช้บน MySQL ล้วนๆ (ไม่ได้ใช้ Supabase)
--ใช้สคริปต์ชุดนี้สำหรับ MySQL Database:
/*SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `Cafe_Amazon_Bill`;
DROP TABLE IF EXISTS `Cafe_Amazon_Promosion_House`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `Cafe_Amazon_Promosion_House` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Detail` VARCHAR(50) NULL DEFAULT NULL,
  `Remark` VARCHAR(255) NULL DEFAULT NULL,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `Phone_No` VARCHAR(13) NULL DEFAULT NULL,
  `Day_Limit` INT NULL DEFAULT NULL,
  `All_Limit` INT NULL DEFAULT NULL,
  `All_Use` INT NULL DEFAULT 0,
  `LastUse_Date` DATETIME NULL DEFAULT NULL,
  `IsUse` TINYINT(1) NOT NULL DEFAULT 0,
  `InsertDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `InsertUser` VARCHAR(20) NULL DEFAULT NULL,
  `UpdateDate` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `UpdateUser` VARCHAR(20) NULL DEFAULT NULL,
  `PassWord` VARCHAR(255) NULL DEFAULT NULL,
  `Confirm_Coupon` TINYINT(1) NOT NULL DEFAULT 0,
  `Coupon_No` VARCHAR(50) NULL DEFAULT NULL,
  `Product_ID` VARCHAR(13) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UX_CafeAmazonHouse_Phone` (`Phone_No`),
  INDEX `idx_coupon_no` (`Coupon_No`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `Cafe_Amazon_Bill` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Bill_No` VARCHAR(50) NULL DEFAULT NULL,
  `Cafe_Amazon_PK` INT NULL DEFAULT NULL,
  `Product_Type` VARCHAR(13) NULL DEFAULT NULL,
  `ItemDetail` TEXT NULL,
  `Price` DECIMAL(10,2) NULL DEFAULT 0.00,
  `Discount` DECIMAL(10,2) NULL DEFAULT 0.00,
  `Change` DECIMAL(10,2) NULL DEFAULT 0.00,
  `InsertDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `IsUse` TINYINT(1) NULL DEFAULT 1,
  `Coupon_No` VARCHAR(50) NULL DEFAULT NULL,
  `Project_ID` VARCHAR(13) NULL DEFAULT NULL,
  "Product_ID" VARCHAR(13) DEFAULT NULL
  PRIMARY KEY (`ID`),
  INDEX `idx_cafe_amazon_pk` (`Cafe_Amazon_PK`),
  CONSTRAINT `fk_bill_house` FOREIGN KEY (`Cafe_Amazon_PK`) REFERENCES `Cafe_Amazon_Promosion_House` (`ID`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
*/
